### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by WangZH525** [hd10-iupui/AttentionRank#2]
I would like to ask how the heat map in Figure 6 and Figure 7 is drawn. Could you share the relevant code? Thanks you.

**Comment by haoranding10** [comment]
To be honest, Fig.6 and Fig.7 are not generated by some tool. I made them using Office Word. Calculate importance for each candidate and then color them by hand. Sorry I didn't help you.

**Comment by WangZH525** [comment]
Thanks for your reply. And it is truly helpful for me.
