### ISSUE TITLE
Regarding possible issue in 011_normed_integration.py

### ISSUE THREAD

**Issue by anand-subu** [hd10-iupui/AttentionRank#4]
Hi there, I was interested in your work regarding AttentionRank. I had a doubt about a possible issue in **011_normed_integration.py**.  

In lines 104-106:
```
for k, v in cross_attn_dict.items():
        cross_attn_dict[k] = \
            (v - min(cross_attn_dict.values())) / (max(cross_attn_dict.values()) - min(cross_attn_dict.values()))
```

and in lines 133-138

```    for k, v in accumulated_self_attn_dict.items():

        if k in cross_attn_dict.keys() and k.split(' ')[0] not in stopwords:
            accumulated_self_attn_dict[k] = \
                (v - min(accumulated_self_attn_dict.values())) / (max(accumulated_self_attn_dict.values()) - min(accumulated_self_attn_dict.values()))
            ranking_dict[k] = accumulated_self_attn_dict[k] * (t) / 10 + cross_attn_dict[k] * (10 - t) / 10
```

I believe the intention is to perform min-max normalization on the cross attention and self attention values. However **cross_attn_dict** and **accumulated_self_attn_dict** is dynamically updated inside each loop. This would affect the calculation of min(dict.values()) and max(dict.values()) since the values would change as the dictionary gets updated. 

Could you clarify if this is a potential issue, or if this is by design?

**Comment by haoranding10** [comment]
Yes, you are correct. It is indeed a mistake.  On my own computer, I compute the min and max first. However, for the upload version, I made these negative code revision. Just fixed. Thank you so much figuring out these!

**Comment by anand-subu** [comment]
Ah, thanks for clarifying! I'll close this ticket then.
