### ISSUE TITLE
Need requirement.txt

### ISSUE THREAD

**Issue by WanBenLe** [hd10-iupui/AttentionRank#6]
I can not run 

import mxnet as mx
from bert_embedding import BertEmbedding

can you give me the requirement.txt witch had package version?
Thanks

**Comment by WanBenLe** [comment]
The error in from bert_embedding import BertEmbedding like this

--import numba.core.types as types
AttributeError: module 'numba' has no attribute 'core'
AttributeError: module 'numpy' has no attribute 'gcd'

**Comment by WanBenLe** [comment]
An other question is the code of [AttentionRank](https://github.com/hd10-iupui/AttentionRank/tree/a61e60e66bd71ad98c3e2a58863daf0ef7240086)/009_doc_embedding.py

`sentences_with_embeddings = bert(sentences)  # this bert handle [list of sentences]

        for l, sentence_with_embeddings in enumerate(sentences_with_embeddings):

            words = sentence_with_embeddings[0]

            embeddings = sentence_with_embeddings[1]

            w0 = csv.writer(open(save_path + file + '_sentence' + str(l) + '_word_embeddings.csv', "a"))

            for i in range(len(words)):

                w0.writerow([words[i], embeddings[i]])

    print(n + 1, "th file", file, "running time", time.time() - start_time)`


It means  write the last_hidden_state(dims=sents of doc * words of sent * 768 ,not the result of pooling which dim=sents of doc * 768) to the csv file?

**Comment by DavideZanutto** [comment]
I managed to make it work, I attach the requirements I used here, could be helpful
[requirements.txt](https://github.com/hd10-iupui/AttentionRank/files/14361917/requirements.txt)

**Comment by haoranding10** [comment]
Thanks Davide! Do you mind if I add your "requirements.txt" to the files? @DavideZanutto

**Comment by haoranding10** [comment]
Yes, this step saves word-level embeddings, and generates sentence embeddings and document embeddings in the next step. @WanBenLe

**Comment by DavideZanutto** [comment]
@hd10-iupui Yeah go ahead
